// <auto-generated />
namespace SMS_Sender.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AgregarTablaCliente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AgregarTablaCliente));
        
        string IMigrationMetadata.Id
        {
            get { return "201805061418296_AgregarTablaCliente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
